"""
Build a double-clickable macOS app, "Lunoviq Valuation.app", with its own icon.

The app starts the local web server in the background (no Terminal window)
if it is not already running, waits for it, and opens the browser. The server
keeps running until "Quit" is chosen in the web app or the Mac restarts.
Log: ~/Library/Logs/Lunoviq.log

Usage:
    python tools/make_mac_app.py [--dest ~/Applications]
"""
import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PORT = 8765

LAUNCHER = """#!/bin/bash
# Lunoviq Valuation.app launcher (generated by tools/make_mac_app.py)
PROJECT="{project}"
PY="{python}"
URL="http://127.0.0.1:{port}"
LOG="$HOME/Library/Logs/Lunoviq.log"

if ! /usr/bin/curl -s -o /dev/null -m 2 "$URL/api/history"; then
  if [ ! -d "$PROJECT" ]; then
    /usr/bin/osascript -e 'display alert "Lunoviq" message "Project folder not found: {project}. Rebuild the app with tools/make_mac_app.py."'
    exit 1
  fi
  cd "$PROJECT" || exit 1
  echo "--- start $(date)" >> "$LOG"
  nohup "$PY" -W ignore -m lunoviq serve --no-browser --port {port} >> "$LOG" 2>&1 &
  for i in $(seq 1 60); do
    /usr/bin/curl -s -o /dev/null -m 1 "$URL/" && break
    sleep 0.5
  done
fi
/usr/bin/open "$URL"
"""

PLIST = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>Lunoviq Valuation</string>
  <key>CFBundleDisplayName</key><string>Lunoviq Valuation</string>
  <key>CFBundleIdentifier</key><string>com.lunoviq.app</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>Lunoviq</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSAppleEventsUsageDescription</key><string>Lunoviq uses Microsoft Excel to recalculate valuation models.</string>
</dict></plist>
"""


def draw_icon(path, size=1024):
    """Brand mark: navy rounded square, light-blue lower-right triangle, white bar chart."""
    from PIL import Image, ImageDraw
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    pad, r = int(size * 0.09), int(size * 0.2)
    box = (pad, pad, size - pad, size - pad)
    d.rounded_rectangle(box, r, fill=(31, 95, 139, 255))
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).rounded_rectangle(box, r, fill=255)
    tri = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    ImageDraw.Draw(tri).polygon([(size - pad, pad), (size - pad, size - pad), (pad, size - pad)],
                                fill=(169, 199, 221, 255))
    img.paste(tri, (0, 0), Image.composite(tri.split()[3], Image.new("L", (size, size), 0), mask))
    # three rising bars
    base, w, gap = size - pad - int(size * 0.2), int(size * 0.11), int(size * 0.05)
    x0 = int(size * 0.27)
    for i, h in enumerate((0.18, 0.30, 0.44)):
        x = x0 + i * (w + gap)
        d.rounded_rectangle((x, base - int(size * h), x + w, base), int(w * 0.18), fill=(255, 255, 255, 255))
    img.save(path)


def build(dest):
    dest = Path(os.path.expanduser(dest))
    app = dest / "Lunoviq Valuation.app"
    if app.exists():
        shutil.rmtree(app)
    (app / "Contents" / "MacOS").mkdir(parents=True)
    (app / "Contents" / "Resources").mkdir()
    (app / "Contents" / "Info.plist").write_text(PLIST)
    exe = app / "Contents" / "MacOS" / "Lunoviq"
    python = "/opt/anaconda3/bin/python3" if Path("/opt/anaconda3/bin/python3").exists() else sys.executable
    exe.write_text(LAUNCHER.format(project=ROOT, python=python, port=PORT))
    exe.chmod(0o755)

    with tempfile.TemporaryDirectory() as tmp:
        png = Path(tmp) / "icon.png"
        draw_icon(png)
        iconset = Path(tmp) / "AppIcon.iconset"
        iconset.mkdir()
        for s in (16, 32, 128, 256, 512):
            for scale in (1, 2):
                name = "icon_%dx%d%s.png" % (s, s, "@2x" if scale == 2 else "")
                subprocess.run(["sips", "-z", str(s * scale), str(s * scale), str(png),
                                "--out", str(iconset / name)], check=True, capture_output=True)
        subprocess.run(["iconutil", "-c", "icns", str(iconset),
                        "-o", str(app / "Contents" / "Resources" / "AppIcon.icns")], check=True)
        shutil.copy(png, ROOT / "docs" / "lunoviq_icon.png")
    subprocess.run(["touch", str(app)], check=False)          # refresh Finder's icon cache
    print("Built", app)
    return app


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--dest", default="~/Applications")
    build(ap.parse_args().dest)
